### ISSUE TITLE
Error when adding rule

### ISSUE THREAD

**Issue by bigrob69** [sensepost/ruler#53] opened 2017-09-13 07:50 UTC
Hi Staaldraad

I get the following error when attempting to display rules via RPC. 

[+] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
[+] Retrieving Rules
ERROR: 2017/09/13 07:39:12 mapi: non-zero return value. ERROR_CODE: 4b9 - {CODE_NOT_FOUND}

Upon attempting to add a rule I get the following:

[+] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
[+] Adding Rule
[+] Rule Added. Fetching list of rules...
[*] And disconnecting from server

However ,I can confirm via mailbox access that the rule has not been created.

Any thoughts ?

**Comment by staaldraad** [comment] 2017-09-13 07:59
Hi! 

I've got a few thoughts, it could be that the RPC response is "too large" - there are possibly more rules set than expected. Alternatively you have an older version of ruler - the 4b9 indicates a bad parse of the response buffer

Which version of Ruler are you using? You could try the latest and include the ```--debug``` flag - although I think  it's not going to give the info we need.

The new version I'm releasing end of the month should help here, but maybe we can figure this out before then.

What is the result when you try display forms?

cheers,

**Comment by bigrob69** [comment] 2017-09-13 08:21
Thanks for the snappy reply.

I am using the ruler-linux64 - 2.1.7 binary
I know from mailbox access that there aren't any rules configured. 

Displaying forms gives the following:

[*] Got Context, Doing ROPLogin
[*] And we are authenticated
[*] Openning the Inbox
[+] No Forms Found
[*] And disconnecting from server

**Comment by staaldraad** [comment] 2017-09-13 08:29
Could you ping me at etienne[at]sensepost.com ? I'll send you a link to a preview build of the latest version with better debugging - and we can figure it out from there

**Comment by staaldraad** [comment] 2017-09-30 13:45
I'm going to close this for now, haven't been able to reproduce. Since rules are being blocked more often now, feel this moves down the priority list of attack options

**Closed by staaldraad** 2017-09-30 13:45 UTC
Labels: bug
