### ISSUE TITLE
Error building ruler

### ISSUE THREAD

**Issue by Raikia** [sensepost/ruler#109] opened 2020-02-12 17:45 UTC
I can't seem to get Ruler to build using the command:

    go get github.com/sensepost/ruler

![img](https://i.imgur.com/S3y8PzL.jpg)

I'm quite unfamiliar with Go so I apologize if I'm missing something basic, but I'm just following the "Getting Started" wiki page

**Comment by staaldraad** [comment] 2020-02-17 18:03
Hi 👋 

This should be resolved, the issue is due to the dependency being converted to a go module, as noted in this merged PR: https://github.com/sensepost/ruler/pull/104 

you could try with `GO111MODULE=auto`

**Closed** 2020-05-03 10:02 UTC
